import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend | mentor",
  description: "Generated by create next app",
  icons: { icon: "/favicon-32x32.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-custom-bg  relative`}>
        {children}
      </body>
    </html>
  );
}
